{% set version = '1.0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-semaphore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/semaphore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/semaphore/semaphore_{{ version }}.tar.gz
  sha256: 017443979225724eeb7060bf8c6effa0b89abef2040acfdff83bf1fd0f0675e6

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib('c') }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    #- r-bh
    - r-rcpp

test:
  commands:
    - $R -e "library('semaphore')"           # [not win]
    - "\"%R%\" -e \"library('semaphore')\""  # [win]

about:
  home: https://cmmr.github.io/semaphore/, https://github.com/cmmr/semaphore
  license: MIT
  summary: Implements named semaphores from the 'boost' 'C++' library <https://www.boost.org/>.
    A semaphore object is shared amongst several processes. This integer value can be
    safely incremented or decremented by each processes. Processes can also wait (blocking)
    for the value to become non-zero.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - dansmith01
    - conda-forge/r

# Package: semaphore
# Type: Package
# Title: Shared Memory Atomic Operations
# Version: 1.0.2
# Date: 2024-11-12
# Authors@R: c( person( "Daniel P.", "Smith", email   = "dansmith01@gmail.com", role    = c("aut", "cre"), comment = c(ORCID = "0000-0002-2479-2044")), person( "Alkek Center for Metagenomics and Microbiome Research", role = c("cph", "fnd") ))
# Description: Implements named semaphores from the 'boost' 'C++' library <https://www.boost.org/>. A semaphore object is shared amongst several processes. This integer value can be safely incremented or decremented by each processes. Processes can also wait (blocking) for the value to become non-zero.
# URL: https://cmmr.github.io/semaphore/, https://github.com/cmmr/semaphore
# BugReports: https://github.com/cmmr/semaphore/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# Config/testthat/edition: 3
# LinkingTo: Rcpp, BH
# Imports: Rcpp
# Suggests: testthat
# NeedsCompilation: yes
# Packaged: 2024-11-12 23:01:17 UTC; Daniel
# Author: Daniel P. Smith [aut, cre] (<https://orcid.org/0000-0002-2479-2044>), Alkek Center for Metagenomics and Microbiome Research [cph, fnd]
# Maintainer: Daniel P. Smith <dansmith01@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-11-13 08:30:02 UTC
